import 'package:flutter/material.dart';

const blueColor=Color(0xff1FB0FF);
const scaffoldColor=Colors.cyan;//Color(0xff41CDFF);
const payButtonColor=Color(0xff471458);
const coffeeColor= Color(0xff403632);
const lightColor= Colors.white;
const family ="Poppins";
const Governorates=[
'القاهرة',
'الجيزة',
'الأسكندري',
'الدقهلية',
'الشرقية',
'المنوفية',
'القليوبية',
'البحيرة',
'الغربية',
'بور سعيد',
'دمياط',
'الإسماعلية',
'السويس',
'كفر الشيخ',
'الفيوم',
'بني سويف',
'مطروح',
'شمال سيناء',
'جنوب سيناء',
'المنيا',
'أسيوط',
'سوهاج',
'قنا',
'البحر الأحمر',
'الأقصر',
'أسوان',
'الواحات',
'الوادي الجديد',
  'cairo',
  'giza',
  'alexandrian',
  'dakahlia',
  'eastern',
  'monofia',
  'qalyubia',
  'the lake',
  'western',
  'port Said',
  'damietta',
  'ismailia',
  'suez',
  'kafr El-Sheikh',
  'fayoum',
  'bani Sweif',
  'subtracted',
  'north Sinai',
  'south of Sinaa',
  'minya',
  'asyut',
  'sohag',
  'qena',
  'the Red Sea',
  'the shortest',
  'aswan',
  'oases',
  'the new Valley',
];
